import cv2
from pyaudio import PyAudio, paInt16

Model = "./Model/20180408-102900.pb"
Emotion_model_path = './gae/fer2013_mini_XCEPTION.110-0.65.hdf5'
Gender_model_path = './gae/gender_mini_XCEPTION.2878-0.93.hdf5'
JsonFilePath = "./gae/WRN_16_2.json"
WeightFilePath = "./gae/weights.25000-0.03.hdf5"
EmotionData = "KDEF"
GenderData = "imdb"
DescribePeople = ["A","B","C","D","E","F","G","H","I","J","K","O","M","N"]
SinglePerson = ["你好，很高兴见到你，",'你好啊！今天是怎么来的呢？骑自行车？还是坐地铁？',"今天没跟朋友一起来吗？还好你有我","就一个人来的吗？我可以跟你在一起哦"] 
ManyPeoples = ["哈哈哈！来了这么多人啊！","大家好！我是赛恩斯机器人，我也好想加入你们啊！","这么多人都来看我表演吗？我可要努力啦！","这么多人来，我有点慌张啊！"]
Anger = ["莫生气，气坏身体谁如意，开心点。","你在生气？注意血压啊！","生气还是在跟我扮鬼脸?","看看今天周几啦！不要发脾气哦"]
Dis = ["不要用怀疑的眼光看我哦。","说不上来，你是在质疑我吗？","你在怀疑谁？人工智能？","批判的眼光看一切，但是不要小瞧新氦。","你在质疑我的智商？我可是机器人哎。"]
Fear = ["你在害怕吗？抱紧小姐姐就对了。","解决恐惧的办法就是面对他。","来到新氦就不用害怕啦，这里有你想要的一切。","你在担心我会跳出来吗？我还没有经过图灵测试。","可以用你的表情做一个表情包啦。"]
Happy = ["看到你开心，我也就开心啦。","开心就对了，这里可是新氦。","你怎么这么开心，快给我讲讲。","开心会让你变得更加年轻哦。","来到新氦类脑就会变得开心。","你在冲我笑的时候，会想把我带回家吗？"]
Sad = ["你在悲伤什么呢？说出来让我开心一下。","悲伤逆流成河，回到新氦了吗？哈哈哈","是因为我没有冲你笑，所以你悲伤吗？","哈哈哈哈哈，跟我学一遍。","你都有我了还悲伤什么呢？"]
Supers = ["你惊喜的表情，我已经留做表情包啦！","看见我你很惊喜？","惊喜的不仅仅是你，我也是第一次看见这么多的人","新氦类脑带给你的不仅仅是惊喜哦"]
Nature = ["我喜欢你平和的心态。","看你平静的内心，我觉得可以来一杯咖啡","就一个表情吗？你可以对我掘掘嘴","你猜我会怎么评价你的长相？有点可爱。","来来动起来你的面部肌肉，笑一笑。"]
FuDan = "我是您的新朋友赛斯,我是一个会卖萌的景区服务智能管家,我不仅可以引领接待客人和语音聊天,我还可以做您的景区导航,并且提供全年365天全天24小时无休服务,节假日从不请假,可谓是新一代的劳模！请问有什么可以帮助您的吗？"
ErrorAns = ["非常抱歉，您的问题超出赛斯的能力范围，您可以询问我的主人。","不好意思，您能再说一遍吗？","抱歉，可以打断一下吗？能不能请您说慢一点？赛斯已经竭尽全力了，还是跟不上您的节奏。"]
AddWords = ["您的问题太智能了，我得记下来","我光注意你的，愣了个神，您刚才说什么？","一千个问题有一千种回答，但是我该回答哪个呢？","对我太苛刻了，莹莹莹！换个问题吧"]
KeyWords = ["年纪","年龄","性别","岁","男女","男","女","多大","今年","几岁","年"]
KeyContents = ["我看见你大概在","我是用我的AI眼睛看见你可能在","我拿眼睛猜测你也许在"]
EmoDic = {'AN':Anger, 'DI':Dis, 'AF':Fear, 'HA':Happy, 'SA':Sad, 'SU':Supers, 'NE':Nature}
Leave = ["您怎么走了啊？不再聊会了吗？","怎么走了啊，我还没看够你呢","想走了吗？","不许走哦，我可一直看着你呢啊","我可看着你呢啊，再陪我聊一会吧","往我这里看，不许走哦"]
Return = ["哈哈哈，您又回来啦！","谢谢，继续跟我聊天哦","我看见您刚才走了，怎么又回来啦！","回来的刚好，可以跟我聊一聊","我看你刚才要走，又回来了是想我了吗？！"]
Normal = ["我看见你正对着我啦","哈哈哈，你正对着我，我就看的更仔细了","看你认真跟我聊天的样子，真优秀","你可不要走哦！我可是能看见你晃头的哦","你可以假装离开，看我挽留你吗","我能看见你的年龄哦，快问问我"]

OnlyPeople = ["我看见今天现场就您一个人来的啊！","虽然我看见您是一个人来的，但是还好有我陪着你","您是一个人来的啊！让我看看我能看出些什么呢"]
OnlyMan = ["我怎么只能看见男生啊！","这里只有男生啊！","不开心，没有小姐姐吗？","这里只有男生啊！但是我想看见女孩子啊！"]

EmoE2C = {'AN':"生气",'DI':"怀疑",'AF':"恐惧",'HA':"开心",'SA':"悲伤",'SU':"惊喜",'NE':"自然"}

TurnHead = {"Leave":Leave,"Return":Return,"Normal":Normal}
RenImage = "Render.png"
Listen = "识别中"
Speak = "请讲话"
APP_ID = "20168551"
API_KEY = "hVS3GORgC9rY3QwP0akCm9j4"
SECRET_KEY = "7fVzcGG1Md0fPoGKZ6xS6k6z3LP5EbaT"
SaveAudioMP3 = "./MicData.wav"
Address = "http://39.98.201.50/Lawyer/dialog/getDialogResponse"
SessionID = "89229089de3743fe8bf3f58e22999a98"
Post_header = {"Content-Type":"application/json","Accept":"*/*"}
Sleep = [1,3,3.3,5,4.5]
Step = ["B","B","B","B"]
FontSize = 30
Row = 960
Column = 1000
TimeOut = 1
ReVoiNum = 10
TempNum = 100
CHUNK = 1024
FORMAT = paInt16
CHANNELS = 2
RATE = 44100
RECORD_SECONDS = 3  #设置录音的时间长度
ConvertRate = 16000
MeanNum = 4
Ratio = 0.6
VoiceThreshold = 30
NUM_SAMPLES = 500
SendPlaceHold = 3
EmotionSmooth = 3
DelEmotionPara = 10
SubPix = 127.5
Coeffe = 0.0078125
AgeSize = 64
gpu_memory_fraction = 0.8
image_size = 160
margin = 40
minsize = 20 # minimum size of face
threshold = [ 0.6, 0.7, 0.7 ]  # three steps's threshold
factor = 0.709 # scale factor
Font=cv2.FONT_HERSHEY_COMPLEX_SMALL
Font_scale = 1
Thickness = 1
Color = (234,124,35)
DelPeople = 70
gender_offsets = (30, 60)
emotion_offsets = (20, 40)
age_offsets =(0,0)
offsets_list = [age_offsets,gender_offsets,emotion_offsets]
